development:
          adapter: postgresql
          database: ndt_app_v6_development
          host: localhost
          
test:
        adapter: postgresql
        database: ndt_app_v6_test
        host: localhost